-- +goose Up
CREATE TABLE IF NOT EXISTS course (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  dep_id INT(10) UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (dep_id) REFERENCES department(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +goose Down
DROP TABLE cource;
