-- +GOOSE UP
CREATE TABLE IF NOT EXISTS faculty (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(55) NOT NULL,
  type TINYINT(2) UNSIGNED NOT NULL,
  campus TINYINT(1) UNSIGNED NOT NULL,
  faculty_id INT(10) UNSIGNED DEFAULT NULL,
  department_id INT(10) UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;
/*
type:
    1:キャンパス
    2:学部
    3:学科
 */

-- +GOOSE DOWN
DROP TABLE faculty;
