-- +goose Up
CREATE TABLE IF NOT EXISTS review (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  class_id INT(10) UNSIGNED NOT NULL,
  ease_of_understanding TINYINT(1) UNSIGNED NOT NULL,
  motivation TINYINT(1) UNSIGNED NOT NULL,
  attendence TINYINT(1) UNSIGNED NOT NULL,
  tests_difficulty TINYINT(1) UNSIGNED NOT NULL,
  easiness TINYINT(1) UNSIGNED NOT NULL,
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (class_id) REFERENCES class(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +goose Down
DROP TABLE review;
