version: "3.3"

services:
    mysql: 
        image: mysql:5.7
        restart: always
        container_name: agplus_mysql
        tty: true
        stdin_open: true 
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: agplus
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    server:
        build: .
        tty: true
        stdin_open: true
        privileged: true
        working_dir: /agplus
        ports:
            - "6060:6060"
        volumes:
            - ~/.cache:/root/.cache
            - .:/go/src/agplus
            - $GOPATH/pkg/mod:/go/pkg/mod
            - .:/agplus
        environment:
            - GO111MODULE=on
        depends_on:
            - mysql
        links:
            - mysql

    front:
        image: docker-vue
        build:
            context: .
            dockerfile: ./docker/front/Dockerfile
        container_name: agplus_front
        tty: true
        stdin_open: true
        privileged: true
        ports:
            - "8080:8080"
        depends_on:
          - server
        volumes:
#            - ./:/agplus
            - .:/var/www/docker-vue
            - /var/www/docker-vue/node_modules
        environment:
            - npm_config_unsafe_perm=true
#        command: yarn run serve --port 8080
#        command:  npm run serve --port 8080

    migrate:
        build:
            context: ./db
            dockerfile: Dockerfile
        working_dir: /agplus
        volumes:
            - .:/agplus
        depends_on: 
            - mysql
        command: make migrate-up
