version: "3.3"

services:
    mysql:
        image: mysql:5.7
        restart: always
        container_name: agplus_mysql
        tty: true
        stdin_open: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: agplus
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    server:
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        container_name: agplus_server
        tty: true
        stdin_open: true
        privileged: true
        working_dir: /agplus/server
        ports:
            - "6060:6060"
        volumes:
            - ~/.cache:/root/.cache
            - .:/go/src/agplus
            - $GOPATH/pkg/mod:/go/pkg/mod
            - .:/agplus
        environment:
            - GO111MODULE=on
        depends_on:
            - mysql
        command:
            - go run *.go

    front:
        image: docker-vue
        build:
            context: .
            dockerfile: ./docker/front/Dockerfile
        container_name: agplus_front
        tty: true
        stdin_open: true
        privileged: true
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www/docker-vue
            - /var/www/docker-vue/node_modules
        environment:
            - npm_config_unsafe_perm=true

    migrate:
        container_name: agplus_migrate
        build:
            context: .
            dockerfile: ./docker/db/Dockerfile
        working_dir: /agplus
        volumes:
            - .:/agplus
        depends_on:
            - mysql
        entrypoint:
            - dockerize
            - -timeout
            - 15s
            - -wait
            - tcp://mysql:3306
        command: goose up
