version: "3.3"

services:
    mysql: 
        image: mysql:5.7
        restart: always
        container_name: agpluss_mysql
        tty: true
        stdin_open: true 
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: agpluss
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    app:
        # image: golang:latest
        build: .
            # context: ./docker/app/
            # dockerfile: Dockerfile
        tty: true
        stdin_open: true
        privileged: true
        # container_name: agpluss_app
        working_dir: /agpluss
        ports:
            - 6060:6060
        volumes:
            - ~/.cache:/root/.cache
            - .:/go/src/agpluss
            - $GOPATH/pkg/mod:/go/pkg/mod
            - .:/agpluss
        environment:
            - GO111MODULE=on
        depends_on:
            - mysql
        links:
            - mysql
        # command: 
             # sudo apt-get update
             # sudo apt-get install -y mysql-client
             # go get -u bitbucket.org/liamstask/goose/cmd/goose
             # make migrate/up
        # command: make migrate-up 
    
    migrate:
        build:
            context: ./db
            dockerfile: Dockerfile
        working_dir: /agpluss
        volumes:
            - .:/agpluss
        depends_on: 
            - mysql
        command: make migrate-up
