FROM node:latest

COPY package*.json /app

RUN apt-get update
RUN npm install npm@latest -g
RUN npm install
#RUN npm install yarn
#RUN apt-get install -y npm
#RUN apt-get install -y vim
#RUN apt-get install -y git
#RUN npm install @vue/cli
#RUN git clone https://github.com/k-ueki/AGPluss.git

