# FROM nginx:latest
#
# RUN apt-get update
# RUN apt-get install -y yarn
FROM node:11.1

# RUN apt-get update
# RUN apt-get install -y curl
# RUN curl -SL https://deb.nodesource.com/setup_13.x | bash
# RUN apt-get install -y nodejs
# RUN npm install npm@latest -g
# RUN npm install -g @vue/cli
#
# WORKDIR /app
# RUN yarn install

# EXPOSE 8080
# CMD ["yarn", "serve"]
