name: Test
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.6'

      - name: Setup Repository
        run: |
          git clone https://github.com/k-ueki/AGPlus.git
          go get github.com/jinzhu/gorm
          go get -u github.com/k-ueki/AGPlus/server/domain/model
          go get -u github.com/DATA-DOG/go-sqlmock
          go get github.com/golang/mock/mockgen
          go get github.com/golang/mock/gomock
          go get github.com/pkg/errors

      - name: Go Repository Test
        run: go test ./AGPlus/server/adaptor/repository -v
